force-app/main/default/objects/Airplane__c/Airplane__c.object-meta.xml
<CustomObject>
    <label>Airplane</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Airplane Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Airplanes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Airplane__c/fields/Last_Contact__c.field-meta.xml
<CustomField>
    <fullName>Last_Contact__c</fullName>
    <description>Unix timestamp (seconds) for the last update in general. This field is updated for any new, valid message received from the transponder.</description>
    <label>Last Contact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Airplane__c/fields/Time_Position__c.field-meta.xml
<CustomField>
    <fullName>Time_Position__c</fullName>
    <description>Unix timestamp (seconds) for the last position update. Can be null if no position report was received by OpenSky within the past 15s.</description>
    <label>Time Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AirplaneTriggerHandler.cls
public with sharing class AirplaneTriggerHandler extends TriggerHandler {
    
    public override void beforeInsert() {
        for(Airplane__c airplane : (List<Airplane__c>) Trigger.new) {
          if (airplane.Timestamp__c != null) {
            Long timestamp = 1000L * (Long) airplane.Timestamp__c.getTime();
            airplane.Timestamp__c = datetime.newInstance(timestamp);
          }
          if (airplane.Last_Contact__c != null) { 
            Long lastContactTimestamp = 1000L * (Long) airplane.Last_Contact__c;
            airplane.Last_Contact__c = lastContactTimestamp;
          }
          if (airplane.Time_Position__c != null) {
            Long timePositionTimestamp = 1000L * (Long) airplane.Time_Position__c;
            airplane.Time_Position__c = timePositionTimestamp;
          }
        }
      }

      public override void beforeUpdate() {
        for(Airplane__c airplane : (List<Airplane__c>) Trigger.new) {
          if (airplane.Timestamp__c != null && String.valueOf(airplane.Timestamp__c).length() < 13) {
            Long timestamp = 1000L * (Long) airplane.Timestamp__c.getTime();
            airplane.Timestamp__c = datetime.newInstance(timestamp);
          }  
          if (airplane.Last_Contact__c != null && String.valueOf(airplane.Last_Contact__c).length() < 13) {
              Long lastContactTimestamp = 1000L * (Long) airplane.Last_Contact__c;
              airplane.Last_Contact__c = lastContactTimestamp;
            }
            if (airplane.Time_Position__c != null && String.valueOf(airplane.Time_Position__c).length() < 13) {
              Long timePositionTimestamp = 1000L * (Long) airplane.Time_Position__c;
              airplane.Time_Position__c = timePositionTimestamp;
            }
        }
      }

}